name: Release
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{steps.release-please.outputs.release_created}}
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: go
          manifest-file: .github/.release-please-manifest.json
          target-branch: master
  release:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release_created
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{github.token}}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{github.token}}
